from PyQt4 import QtGui

from PyQt4.Qsci import QsciLexerXML

propertyID = {'ASPPythonTripleSingleQuotedString': 112, 
                'JavaScriptCommentDoc': 44, 
                'PHPKeyword': 121, 
                'ASPPythonTripleDoubleQuotedString': 113, 
                'VBScriptUnclosedString': 77, 
                'ASPJavaScriptNumber': 60, 
                'PHPOperator': 127, 
                'PythonFunctionMethodName': 100, 
                'PythonTripleDoubleQuotedString': 98, 
                'PythonIdentifier': 102, 
                'ASPJavaScriptWord': 61, 
                'PHPVariable': 123, 
                'ASPPythonKeyword': 111, 
                'ASPPythonFunctionMethodName': 115, 
                'HTMLValue': 19, 
                'HTMLNumber': 5, 
                'HTMLSingleQuotedString': 7, 
                'JavaScriptNumber': 45, 
                'PythonTripleSingleQuotedString': 97, 
                'CDATA': 17, 
                'ASPJavaScriptStart': 55, 
                'ASPVBScriptComment': 82, 
                'HTMLComment': 9, 
                'ASPVBScriptNumber': 83, 
                'ASPJavaScriptSymbol': 65, 
                'JavaScriptSymbol': 50, 
                'PHPSingleQuotedString': 120, 
                'Attribute': 3, 
                'VBScriptStart': 70, 
                'PHPDefault': 118, 
                'ASPVBScriptUnclosedString': 87, 
                'PythonNumber': 93, 
                'ASPVBScriptStart': 80, 
                'SGMLParameterComment': 30, 
                'PHPCommentLine': 125, 
                'ASPStart': 16, 
                'ASPVBScriptIdentifier': 86, 
                'SGMLEntity': 28, 
                'VBScriptKeyword': 74, 
                'HTMLDoubleQuotedString': 6, 
                'Script': 14, 
                'XMLEnd': 13, 
                'Tag': 1, 
                'SGMLError': 26, 
                'ASPVBScriptKeyword': 84, 
                'JavaScriptKeyword': 47, 
                'JavaScriptWord': 46, 
                'ASPPythonOperator': 116, 
                'ASPJavaScriptKeyword': 62, 
                'ASPVBScriptDefault': 81, 
                'PythonKeyword': 96, 
                'UnknownTag': 2, 
                'ASPJavaScriptUnclosedString': 66, 
                'Entity': 10, 
                'ASPPythonComment': 107, 
                'VBScriptIdentifier': 76, 
                'PHPDoubleQuotedString': 119, 
                'XMLTagEnd': 11, 
                'ASPXCComment': 20, 
                'SGMLDoubleQuotedString': 24, 
                'VBScriptString': 75, 
                'JavaScriptComment': 42, 
                'ASPPythonStart': 105, 
                'JavaScriptDefault': 41, 
                'PHPDoubleQuotedVariable': 126, 
                'SGMLBlockDefault': 31, 
                'PythonDefault': 91, 
                'ASPPythonIdentifier': 117, 
                'ASPPythonNumber': 108, 
                'JavaScriptDoubleQuotedString': 48, 
                'JavaScriptSingleQuotedString': 49, 
                'PythonDoubleQuotedString': 94, 
                'ASPJavaScriptSingleQuotedString': 64, 
                'PHPStart': 18, 
                'SGMLParameter': 23, 
                'SGMLSpecial': 27, 
                'VBScriptNumber': 73, 
                'SGMLComment': 29, 
                'ASPJavaScriptRegex': 67, 
                'JavaScriptUnclosedString': 51, 
                'SGMLDefault': 21, 
                'SGMLSingleQuotedString': 25, 
                'Default': 0, 
                'ASPJavaScriptComment': 57, 
                'SGMLCommand': 22, 
                'PythonClassName': 99, 
                'ASPJavaScriptDoubleQuotedString': 63, 
                'ASPPythonClassName': 114, 
                'OtherInTag': 8, 
                'PHPNumber': 122, 
                'VBScriptComment': 72, 
                'ASPPythonDoubleQuotedString': 109, 
                'ASPPythonSingleQuotedString': 110, 
                'PHPComment': 124, 
                'PythonOperator': 101, 
                'VBScriptDefault': 71, 
                'PythonComment': 92, 
                'JavaScriptRegex': 52, 
                'ASPVBScriptString': 85, 
                'UnknownAttribute': 4, 
                'ASPJavaScriptDefault': 56, 
                'ASPAtStart': 15, 
                'ASPJavaScriptCommentLine': 58, 
                'ASPPythonDefault': 106, 
                'PythonStart': 90, 
                'JavaScriptCommentLine': 43, 
                'PythonSingleQuotedString': 95, 
                'XMLStart': 12, 'JavaScriptStart': 40, 
                'ASPJavaScriptCommentDoc': 59}

def styleDescriptions():
    return propertyID.keys()


def defaultStyle():
    defaultStyle = {'Entity': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'PHPComment': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'Script': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'PythonComment': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'ASPVBScriptComment': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'XMLEnd': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'JavaScriptCommentDoc': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'PythonNumber': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPPythonIdentifier': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'VBScriptKeyword': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'SGMLBlockDefault': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPVBScriptDefault': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'SGMLSpecial': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPXCComment': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'JavaScriptRegex': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPJavaScriptComment': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'PHPDoubleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'PythonTripleDoubleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'SGMLDoubleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'ASPJavaScriptDoubleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'PHPDefault': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'SGMLError': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'JavaScriptKeyword': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPPythonTripleDoubleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'PHPCommentLine': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'ASPPythonStart': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'JavaScriptWord': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'PythonTripleSingleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'HTMLValue': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPPythonComment': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'JavaScriptSymbol': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'JavaScriptCommentLine': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'ASPPythonDoubleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'ASPVBScriptString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'HTMLComment': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'VBScriptNumber': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'HTMLDoubleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'PythonIdentifier': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'SGMLEntity': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'PythonFunctionMethodName': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPJavaScriptUnclosedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'ASPJavaScriptSymbol': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPAtStart': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPPythonDefault': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'PythonDefault': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'UnknownAttribute': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPVBScriptUnclosedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'PythonClassName': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'SGMLParameter': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'JavaScriptDefault': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'XMLStart': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'PythonDoubleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'PHPStart': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPVBScriptStart': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'JavaScriptSingleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'OtherInTag': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'JavaScriptUnclosedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'VBScriptIdentifier': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'Default': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'VBScriptDefault': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPStart': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPJavaScriptDefault': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'SGMLSingleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'ASPPythonNumber': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'Attribute': ['Consolas', '#0000ff', 10, False, False, '#ffffff'], 
                    'ASPPythonOperator': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'PythonStart': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'Tag': ['Consolas', '#E72500', 10, False, True, '#ffffff'], 
                    'CDATA': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPPythonSingleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'ASPVBScriptIdentifier': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'UnknownTag': ['Consolas', '#71AB71', 10, False, False, '#ffffff'], 
                    'VBScriptComment': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'ASPJavaScriptCommentLine': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'VBScriptUnclosedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'PHPNumber': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'JavaScriptDoubleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'ASPJavaScriptWord': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'XMLTagEnd': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'SGMLComment': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'SGMLParameterComment': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'VBScriptStart': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'PHPSingleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'ASPPythonFunctionMethodName': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'PythonKeyword': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPJavaScriptNumber': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'PHPKeyword': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'SGMLCommand': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPJavaScriptSingleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'PHPDoubleQuotedVariable': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPJavaScriptCommentDoc': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'ASPVBScriptKeyword': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'SGMLDefault': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'PHPOperator': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'VBScriptString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'ASPPythonKeyword': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPJavaScriptKeyword': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'PythonSingleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'JavaScriptStart': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPJavaScriptStart': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'HTMLSingleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'PHPVariable': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'JavaScriptComment': ['Consolas', '#00B500', 10, False, False, '#ffffff'], 
                    'ASPPythonClassName': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'JavaScriptNumber': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPPythonTripleSingleQuotedString': ['Consolas', '#008100', 10, False, False, '#ffffff'], 
                    'ASPVBScriptNumber': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'ASPJavaScriptRegex': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'HTMLNumber': ['Consolas', '#000000', 10, False, False, '#ffffff'], 
                    'PythonOperator': ['Consolas', '#000000', 10, False, False, '#ffffff']}


    return defaultStyle


class XmlLexer(QsciLexerXML):

    def __init__(self, style, paper):
        QsciLexerXML.__init__(self)

        self.lexerPaper = paper

        for key, attrib in style.items():
            value = propertyID[key]
            self.setColor(QtGui.QColor(attrib[1]), value)
            self.setEolFill(True, value)
            self.setPaper(QtGui.QColor(attrib[5]), value)
            if self.lexerPaper[0] == "Plain":
                self.setPaper(QtGui.QColor(attrib[5]), value)
            else:
                self.setPaper(QtGui.QColor(self.lexerPaper[1]), value)

            font = QtGui.QFont(attrib[0], attrib[2])
            font.setBold(attrib[3])
            font.setItalic(attrib[4])
            self.setFont(font, value)

        if self.lexerPaper[0] == "Plain":
            self.setDefaultPaper(QtGui.QColor("#ffffff"))
        else:
            self.setDefaultPaper(QtGui.QColor(self.lexerPaper[1]))
